/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pfg_gstreamerandroid_MainActivity */

#ifndef _Included_com_pfg_gstreamerandroid_MainActivity
#define _Included_com_pfg_gstreamerandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pfg_gstreamerandroid_MainActivity_PICK_FILE_CODE
#define com_pfg_gstreamerandroid_MainActivity_PICK_FILE_CODE 1L
/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeSetUri
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeSetUri
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativePlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativePlay
  (JNIEnv *, jobject);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeSetPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeSetPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativePause
  (JNIEnv *, jobject);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeClassInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeSurfaceInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeSurfaceInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pfg_gstreamerandroid_MainActivity
 * Method:    nativeSurfaceFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pfg_gstreamerandroid_MainActivity_nativeSurfaceFinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
